"""
Django settings for transport_project project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os #

# Base directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  #

# SECURITY
SECRET_KEY = '_#$lu#*(#b@b09hfvd%txh-v%ru2*4+5lbnz)knw8at11*3z3('
DEBUG = True
ALLOWED_HOSTS = []

# Applications
INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'crispy_forms',  #
    'crispy_bootstrap4',  #
    'mapbox_location_field',  #

    # Local apps
    'account', #
    'main',  #
]

# Custom User model
AUTH_USER_MODEL = 'account.CustomUser'

# Crispy Forms config
CRISPY_TEMPLATE_PACK = 'bootstrap4'   #
CRISPY_ALLOWED_TEMPLATE_PACKS = ['bootstrap4']  #

# Mapbox config
MAPBOX_KEY = "pk.eyJ1IjoiYW1pMjIiLCJhIjoiY2syeTd0dWp3MDM2czNtbW1uaXM5NGg1eSJ9.p1m1QAOWTyk69qGtFtgSJQ"

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL and WSGI
ROOT_URLCONF = 'transport_project.urls'
WSGI_APPLICATION = 'transport_project.wsgi.application'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  #
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static & Media files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] #

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  #

# Login redirects
LOGIN_REDIRECT_URL = 'home' #
LOGOUT_REDIRECT_URL = 'home'  #

# Auto field setting (important for newer Django versions)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
